[project]
name = "svc_platform"
version = "0.54.0"
description = "Платформа для запуска сервисов, `svc_` стандарт (репозитории Mike2024New которые содержат `svc_`"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "infrastructure-server",
    "infrastructure-cli-utils",
    "infrastructure-message-bus",
    "infrastructure-path-utils",
    "infrastructure-http-clients",
    "infrastructure-process-utils",
    "infrastructure-streaming",
    "websockets>=16.1.1",
    "aiohttp>=3.14.3",
]

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "svc_platform*",
]

[tool.uv.sources.infrastructure-server]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_server"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.uv.sources.infrastructure-cli-utils]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_cli_utils"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.uv.sources.infrastructure-message-bus]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_message_bus"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.uv.sources.infrastructure-path-utils]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_path_utils"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.uv.sources.infrastructure-http-clients]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_http_clients"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.uv.sources.infrastructure-process-utils]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_process_utils"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.uv.sources.infrastructure-streaming]
git = "https://github.com/mike2024new/infrastructure2.git"
subdirectory = "packages/infrastructure_streaming"
rev = "b6e936d08871fcda42a5f0c05a629eb2e5cafb1a"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
asyncio_mode = "auto"
pythonpath = [
    ".",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.4.0",
]
