[project]
name = "svc_platform"
version = "0.13.0"
description = "Платформа для запуска сервисов (репозитории svc)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "infrastructure-server",
    "infrastructure-cli-utils",
    "infrastructure-message-bus",
    "infrastructure-path-utils",
    "websockets>=16.1.1",
]

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "svc_platform*",
]

[tool.uv.sources.infrastructure-server]
git = "https://github.com/Mike2024New/infrastructure2.git"
subdirectory = "packages/infrastructure_server"
rev = "0a80e94697ae1390cfabf6c9de448d8f00e285c4"

[tool.uv.sources.infrastructure-cli-utils]
git = "https://github.com/Mike2024New/infrastructure2.git"
subdirectory = "packages/infrastructure_cli_utils"
rev = "0a80e94697ae1390cfabf6c9de448d8f00e285c4"

[tool.uv.sources.infrastructure-message-bus]
git = "https://github.com/Mike2024New/infrastructure2.git"
subdirectory = "packages/infrastructure_message_bus"
rev = "0a80e94697ae1390cfabf6c9de448d8f00e285c4"

[tool.uv.sources.infrastructure-path-utils]
git = "https://github.com/Mike2024New/infrastructure2.git"
subdirectory = "packages/infrastructure_path_utils"
rev = "0a80e94697ae1390cfabf6c9de448d8f00e285c4"

[tool.pytest.ini_options]
testpaths = [
    "svc_platform/tests",
]
pythonpath = [
    ".",
]
